[settings]
lockfile = true

[tools]
dart = { version = "latest", url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-{{ os() }}-{{ arch() }}-release.zip", version_list_url = "https://storage.googleapis.com/storage/v1/b/dart-archive/o?prefix=channels/stable/release/&delimiter=/", version_regex = 'channels/stable/release/(\d+\.\d+\.\d+)/' }
go = "latest"
lua-language-server = "latest"
node = "latest"
npm = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:pyright" = "latest"
"npm:svelte-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
python = "3.12"
rust = "nightly"
uv = "latest"
